# Generated by Django 4.2.18 on 2025-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_city_alter_address_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='product_image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Post Image'),
        ),
    ]
