# Generated by Django 4.2.18 on 2025-02-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_postimage_product_image_postimage_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='post_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='product',
            new_name='post',
        ),
    ]
